### ISSUE TITLE
`IsConsecutiveComment` validation not working with comments inside classes

### ISSUE THREAD

**Issue by JuniorLoch** [franciscobressa/eslint-plugin-avoid-comments#2]
### The plugin cannot properly detect if the comment is to be considered **consecutive** if the comments are inside `classes`

The following example shows this behaviour more clearly:

> [!NOTE]
> I'm using [error-lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) to see the **eslint** errors directly in the editor

![image](https://github.com/franciscobressa/eslint-plugin-avoid-comments/assets/72585178/64a1d91f-41da-452a-ad4a-32a01b5b5291)

**Comment by franciscobressa** [comment]
problem solved my friend
